[package]
name = "tiny-winapi"
version = "0.0.1"
edition = "2018"

[dependencies]
educe = "0.4.16"
null-terminated = "0.3.15"
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "winnt"] }
