[package]
name = "tiny-winapi"
version = "0.1.0"
edition = "2018"

[dependencies]
educe = "0.4.16"
memoffset = { version = "0.6.4", features = ["unstable_const"] }
null-terminated = "0.3.15"
phantom-type = "0.3.0"
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "winnt"] }
